### ISSUE TITLE
Unable to complete flash, memory write failure

### ISSUE THREAD

**Issue by exeljb** [sycophantic/wyzeback#3]
I have the CC1310 Launchpad, trying to flash to one of my contact sensors but am not able to write the file to sensor.  It times out. and I get the errors below.  My launchpad has the TCK pin going to the C pad, the TMS pin going to the M pad.  The 3.3v from the launchpad is going to the + battery terminal and the ground is going to the vbat-.  Is there a trick to allow these chips to take a program load or am I missing something else?

![Screen Shot 2020-12-23 at 5 27 31 PM](https://user-images.githubusercontent.com/59851334/103043934-42752c00-4544-11eb-9de5-4a126de308da.png)

**Comment by exeljb** [comment]
Ok, so I was able to get it to write the flash, I think the problem was the pins weren't making good enough contact with the C and M pads.  It helped to take it out of the case and use some pins that were bent at a 90 degree angle to put more even pressure down on the pads.

**Comment by sycophantic** [comment]
Great! Sorry I didn't respond earlier.
